## remove everything in the working environment.
rm(list=ls())
dat<-read.table("subdat_Tn5.txt",header=TRUE)
head(dat)

N<-length(unique(dat[dat$gene_type==0,1]))
lengthN<- na.omit(  as.numeric( tapply(  dat[dat$gene_type==0,1]  ,  dat[dat$gene_type==0,1] ,length)))
as.numeric(lengthN)

pos_pseudo<-which(dat$gene_type==1)
length_ps<-length(pos_pseudo)
length_ps

#### add a column "ord" to denote normal genes ID and 
#### use the sampe ID for all the pseudogenes.
dat$ord<- N+1
dat$ord[dat$gene_type==0]<-rep( 1:N ,lengthN)

#### design matrix.
X<-model.matrix(~as.factor(dat$match)+ dat$GC_percent)
head(X)
y<-dat$count
### the length of coefficient regression.
nbet<-ncol(X);nbet


## Set initial parameter estimates for EM algorithm.

# mu_initis: initial estimate for mu 
mu_inits = rep(0, N+1)
y_numn0_gene<- tapply(  y>0  ,  dat$ord ,sum)
y_sum_gene<-tapply(  y  ,  dat$ord ,sum)
for(i in 1:(N+1)){
	score_mug<-function(mu)	{
		s=y_sum_gene[i]
		ss=y_numn0_gene[i]
		s/mu - (1/(1- exp(-mu)))* ss	
	}
	
	if( y_sum_gene[i] <=5) mu_inits[i]==0.01
	else mu_inits[i]<- uniroot( score_mug ,interval=c(0.001,10000000))$root
}
mu_inits

# beta_inits: initial estimate for beta
p0 <-  (   sum(y==0)-  exp(- mu_inits) %*%   c(lengthN, length_ps) )/ length(y)
beta_inits <- c(log(p0/(1-p0)), 0,0) 
beta_inits


source("EM_algorithm_withcov.r")
## Run EM Algorithm
output <- em.algo(mu_inits,beta_inits) 
#output$beta
#output$mu

## Obtain variance of parameter estimates
var_dif<-deriv_SD_diff(output$beta,output$mu)
est_dif<- as.numeric(output$mu[1:N])-output$mu[N+1] 


#res: estimate, sd, pvalue, qvalue, type based on q value and estimate
res<-matrix(0,N,5)
res[,1]<-output$mu[1:N]

#standard deviation
res[,2]<- sqrt(var_dif)
#p value
res[,3]<- 2*pnorm(-abs(est_dif/ sqrt(var_dif)))

# q value
res[,4]<-round(p.adjust(res[,3], "BH"), 4)

##  1: hypo-tolerant of transposon insertion.
##  0: tolerant of disruption.
##  2: hyper-tolerant of transposon insertion.
res[,5]<-ifelse(res[,4]<=0.01 & est_dif <=0, 1, 2)
res[ res[, 4]> 0.01, 5]<- 0

res<-cbind(as.character(unique(dat[dat$gene_type==0,1])),res)
colnames(res)<-c("GeneID","est","sd","pvalue","qvalue","essential")
head(res)
write.csv(res,"EM_res.csv",row.names=FALSE)










